### ISSUE TITLE
Unable to install package on cran

### ISSUE THREAD

**Issue by kittysher** [easystats/modelbased#254] opened 2024-05-17 10:45 UTC
Hello,

I am trying to install the whole easystats package but I am getting an error with modelbased which means I can't install the dependencies I need. I am running this on an internal server which doesn't allow me to access github urls. 
When I run
`install.packages("modelbased")`

I get the error:
```
Error in parse(outFile): 
get_marginalmeans.R:50:44: unexpected '>'
49: # Format
50: params <- parameters::parameters(means) |>
                                                                            ^
Unable to collate and parse R files for package 'modelbased'
```

I am using R v4.0.2. Could you please help me work out if this is an issue with the package or an issue somewhere in the internal server?

Many thanks
Kitty

**Comment by bwiernik** [comment] 2024-05-17 11:31
That should be fixed, but the issue is that the package uses the R pipe |>, which was introduced in R 4.1. If you upgrade to the current version of R (4.4) or any version after 4.1, the package will install. 

@strengejacke @IndrajeetPatil @DominiqueMakowski

**Comment by IndrajeetPatil** [comment] 2024-05-17 11:35
This is already fixed on Github: https://github.com/easystats/modelbased/pull/252

We just need to create a new release.

**Comment by strengejacke** [comment] 2024-05-22 08:29
We should wait until https://github.com/easystats/easystats/issues/404 is resolved, there are some places in the code of _modelbased_ where we have to make changes.

**Closed** 2024-07-11 15:21 UTC
